name: Davis Advanced RF Technology Lab
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
gems:
  - jekyll-sitemap
collections:
  publication:
    output: true
  blog:
    output: true
excerpt_separator: <!--more-->
plugins:
  - jekyll-feed
